{
 "title": "FastTechFoods - API Metrics",
 "tags": [
  "fasttechfoods",
  "api",
  "prometheus",
  "metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisições Totais por Serviço",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (http_requests_received_total)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requisições por Status HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total)",
     "legendFormat": "Status {{code}}"
    }
   ]
  },
  {
   "title": "Requisições por Método HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(method) (http_requests_received_total)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Latência (p95) por Serviço",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job))",
     "legendFormat": "{{job}} (p95)"
    }
   ]
  }
 ]
}