global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'menu-service'
    static_configs:
      - targets: ['menu-service:8080']

  - job_name: 'pedido-service'
    static_configs:
      - targets: ['pedido-service:8080']

  - job_name: 'cliente-service'
    static_configs:
      - targets: ['cliente-service:8080']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
